schemaVersion: 1.0.1.3
releaseVersion: 3.2.0
SPECIES: [Species]
BGI: [FB, SGD, WB, ZFIN, RGD, MGI, HUMAN, SARS-CoV-2]
CONSTRUCT: [ZFIN, WB, FB]
ALLELE: [FB, WB, ZFIN, RGD, MGI]
EXPRESSION: [FB, SGD, WB, ZFIN, RGD, MGI]
PHENOTYPE: [FB, SGD, WB, ZFIN, RGD, MGI, HUMAN]
DAF: [FB, SGD, WB, ZFIN, RGD, MGI, HUMAN]
GAF: [FB, SGD, WB, ZFIN, RGD, MGI, HUMAN]
GEOXREF: [FB, SGD, WB, ZFIN, RGD, MGI, HUMAN]
FASTA: [R627, GRCm38, GRCz11, Rnor60, WBcel235]
GENEEEXPRESSIONATLASSITEMAP: [FB, SGD, WB, ZFIN, RGD, MGI, HUMAN]
VARIATION: [FB, WB, ZFIN, RGD, MGI]
GFF: [FB, WB, ZFIN, MGI, RGD, SGD]
AGM: [ZFIN, MGI, RGD, WB]
SQTR: [ZFIN]
HTPDATASET: [SGD, FB, WB, ZFIN, RGD, MGI]
HTPDATASAMPLE: [SGD, FB, WB, ZFIN, RGD, MGI]
ONTOLOGY:
  - SO
  - GO
  - DOID
  - MI
  - ZFA
  - ZFS
  - WBBT
  - CL
  - FBBT
  - FBCV
  - MMUSDV
  - BSPO
  - MMO
  - WBLS
  - EMAPA
  - MA
  - ECO
  - UBERON
  - ECOMAP
  - PATO
  - APO
  - DPO
  - FYPO
  - WBPhenotype
  - MP
  - HP
  - OBI
  - BTO
  - CHEBI
ExpressionAtlas: [FB, SGD, WB, ZFIN, RGD, MGI, HUMAN]
ORTHO: [FB, SGD, WB, ZFIN, RGD, MGI, HUMAN]
ExpressionRibbon: [ExpressionRibbon]
ExpressionRibbonOther: [ExpressionRibbonOther]
GeneDiseaseOrtho: [GeneDiseaseOrtho]
Closure:
  - GO
  - SO
  - DOID
  - MI
  - ZFA
  - ZFS
  - WBBT
  - CL
  - FBBT
  - FBCV
  - MMUSDV
  - BSPO
  - MMO
  - WBLS
  - EMAPA
  - MA
  - ECO
  - UBERON
  - PATO
  - APO
  - DPO
  - FYPO
  - WBPhenotype
  - MP
  - HP
  - OBI
  - BTO
  - CHEBI
INTERACTION-MOL: [COMBINED]
GeneDescriptions: [FB, SGD, WB, ZFIN, RGD, MGI, HUMAN]
VEPTRANSCRIPT: [FB, WB, ZFIN, RGD, MGI]
VEPGENE: [FB, WB, ZFIN, RGD, MGI]
DB-SUMMARY:
  - 3.0.0

# Loader configuration values are below.
# Please modify with caution!

FileTransactorThreads: 10
Neo4jTransactorThreads: 7
