schemaVersion: 1.0.0.7
releaseVersion: 2.1.0.0
BGI: [FB, SGD, WB, ZFIN, RGD, MGI, Human]
Allele: [FB, WB, ZFIN, RGD, MGI]
Expression: [FB, SGD, WB, ZFIN, RGD, MGI]
Phenotype: [FB, SGD, WB, ZFIN, RGD, MGI]
Disease: [FB, SGD, WB, ZFIN, RGD, MGI, Human]
GOAnnot: [FB, SGD, WB, ZFIN, RGD, MGI, Human]
GeoXref: [FB, SGD, WB, ZFIN, RGD, MGI, Human]
Ontology:
  - GO
  - SO
  - DO
  - MI
  - ZFA
  - ZFS
  - WBBT
  - CL
  - FBBT
  - FBCV
  - MMUSDV
  - BSPO
  - MMO
  - WBLS
  - EMAPA
  - MA
  - ECO
  - UBERON
Orthology: [FB, SGD, WB, ZFIN, RGD, MGI, Human]
ExpressionRibbon: [ExpressionRibbon]
GeneDiseaseOrtho: [GeneDiseaseOrtho]
Closure:
  - GO
  - SO
  - DO
  - MI
  - ZFA
  - ZFS
  - WBBT
  - CL
  - FBCV
  - FBBT
  - MMUSDV
  - BSPO
  - MMO
  - WBLS
  - EMAPA
  - MA
  - ECO
  - UBERON
Interactions: [MolecularInteraction]
GeneDescriptions: [FB, SGD, WB, ZFIN, RGD, MGI, Human]

# Loader configuration values are below.
# Please modify with caution!

FileTransactorThreads: 10
Neo4jTransactorThreads: 7
