schemaVersion: 1.0.0.7
releaseVersion: 2.1.0.0
BGI: [FB, SGD, WB, ZFIN, RGD, MGI, Human]
Ontology:
  - GO
  - SO
  - DO
  - MI
  - ZFA
  - ZFS
  - WBBT
  - CL
  - FBDV
  - FBBT
  - FBCV
  - MMUSDV
  - BSPO
  - MMO
  - WBLS
  - EMAPA
  - MA
  - UBERON
  - ECO

# Loader configuration values are below.
# Please modify with caution!

FileTransactorThreads: 10
Neo4jTransactorThreads: 7