schemaVersion:
  regex: ^(\d(\.\d){3})$
  required: True
releaseVersion: 
  regex: ^(\d(\.\d){2})$
  required: True
BGI:
  type: list
  allowed: [FB, SGD, WB, ZFIN, RGD, MGI, HUMAN]
ALLELE:
  type: list
  allowed: [FB, WB, ZFIN, RGD, MGI]
SQTR:
  type: list
  allowed: [ZFIN]
AGM:
  type: list
  allowed: [ZFIN, MGI, RGD]
DAF:
  type: list
  allowed: [FB, SGD, WB, ZFIN, RGD, MGI, HUMAN]
PHENOTYPE:
  type: list
  allowed: [FB, SGD, WB, ZFIN, RGD, MGI]
EXPRESSION:
  type: list
  allowed: [FB, SGD, WB, ZFIN, RGD, MGI]
GAF:
  type: list
  allowed: [FB, SGD, WB, ZFIN, RGD, MGI, HUMAN]
GeoXref:
  type: list
  allowed: [FB, SGD, WB, ZFIN, RGD, MGI, HUMAN]
FASTA:
  type: list
  allowed: [R627, GRCm38, GRCz11, Rnor60, WBcel235]
GENEEEXPRESSIONATLASSITEMAP:
  type: list
  allowed: [FB, SGD, WB, ZFIN, RGD, MGI, HUMAN]
VARIATION:
  type: list
  allowed: [FB, WB, ZFIN, RGD, MGI]
ONTOLOGY:
  type: list
  allowed: 
    - GO 
    - SO
    - DOID
    - MI 
    - ZFA
    - ZFS
    - WBBT
    - CL
    - FBBT
    - FBCV
    - MMUSDV
    - BSPO
    - MMO
    - WBLS
    - EMAPA
    - MA
    - ECO
    - UBERON
    - ECOMAP
ExpressionAtlas:
  type: list
  allowed: [FB, SGD, WB, ZFIN, RGD, MGI, HUMAN]
ORTHO:
  type: list
  allowed: [FB, SGD, WB, ZFIN, RGD, MGI, HUMAN, Human]
ExpressionRibbon:
  type: list
  allowed: [ExpressionRibbon]
ExpressionRibbonOther:
  type: list
  allowed: [ExpressionRibbonOther]
GeneDiseaseOrtho:
  type: list
  allowed: [GeneDiseaseOrtho]
Closure:
  type: list
  allowed: 
    - GO 
    - SO 
    - DOID
    - MI 
    - ZFA 
    - ZFS 
    - WBBT 
    - CL 
    - FBCV
    - FBBT
    - MMUSDV
    - BSPO
    - MMO
    - WBLS
    - EMAPA
    - MA
    - ECO
    - UBERON
Interactions:
  type: list
  allowed: [MolecularInteraction]
GeneDescriptions:
  type: list
  allowed: [FB, SGD, WB, ZFIN, RGD, MGI, HUMAN]
ECOMAP:
  type: list
  allowed: [ECOMAP]
FileTransactorThreads:
  type: integer
  required: True
Neo4jTransactorThreads:
  type: integer
  required: True
